hwtracing: hisi_ptt: Fix up for "iommu/dma: Make header private"
commit 5fc1531dd771cd1481116a66f992a190e01efce6 upstream.

drivers/hwtracing/ptt/hisi_ptt.c:13:10: fatal error: linux/dma-iommu.h: No such file or directory
   13 | #include <linux/dma-iommu.h>
      |          ^~~~~~~~~~~~~~~~~~~

Caused by:

  commit ff0de066b463 ("hwtracing: hisi_ptt: Add trace function support for HiSilicon PCIe Tune and Trace device")

interacting with:

  commit f2042ed21da7 ("iommu/dma: Make header private")

from the iommu tree.

Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>
Acked-by: Robin Murphy <robin.murphy@arm.com>
Acked-by: Yicong Yang <yangyicong@hisilicon.com>
[Fixed subject line and added changelog text]
Signed-off-by: Mathieu Poirier <mathieu.poirier@linaro.org>
Signed-off-by: huwentao <wentaohu0417@163.com>
Signed-off-by: slim6882 <yangjunshuo@huawei.com>
Signed-off-by: Chuyi Zhou <zhouchuyi@bytedance.com>
(cherry picked from commit f71ee7f902f5781fa5ad1e4567c47273faa2eb9f)