bytedance: vdpa: Fix compile errors for vdpa device drivers
Fix some compile errors when enabling the vdpa device drivers:

drivers/vdpa/ifcvf/ifcvf_main.c:743:13: error: initialization of ‘void (*)(struct vdpa_mgmt_dev *, struct vdpa_device *, int)’ from incompatible pointer type ‘void (*)(struct vdpa_mgmt_dev *, struct vdpa_device *)’ [-Werror=incompatible-pointer-types]
  .dev_del = ifcvf_vdpa_dev_del
             ^~~~~~~~~~~~~~~~~~
drivers/vdpa/ifcvf/ifcvf_main.c:743:13: note: (near initialization for ‘ifcvf_vdpa_mgmt_dev_ops.dev_del’)
drivers/vdpa/virtio_pci/vp_vdpa.c:568:13: error: initialization of ‘void (*)(struct vdpa_mgmt_dev *, struct vdpa_device *, int)’ from incompatible pointer type ‘void (*)(struct vdpa_mgmt_dev *, struct vdpa_device *)’ [-Werror=incompatible-pointer-types]
  .dev_del = vp_vdpa_dev_del,
             ^~~~~~~~~~~~~~~
drivers/vdpa/virtio_pci/vp_vdpa.c:568:13: note: (near initialization for ‘vp_vdpa_mdev_ops.dev_del’)
drivers/vdpa/mlx5/net/mlx5_vnet.c:3556:13: error: initialization of ‘void (*)(struct vdpa_mgmt_dev *, struct vdpa_device *, int)’ from incompatible pointer type ‘void (*)(struct vdpa_mgmt_dev *, struct vdpa_device *)’ [-Werror=incompatible-pointer-types]
  .dev_del = mlx5_vdpa_dev_del,
             ^~~~~~~~~~~~~~~~~
drivers/vdpa/mlx5/net/mlx5_vnet.c:3556:13: note: (near initialization for ‘mdev_ops.dev_del’)

Fixes: ae9c56661fdd ("bytedance: vdpa: Add deletion timeout support")
Signed-off-by: Xie Yongji <xieyongji@bytedance.com>